import Head from 'next/head';
import React from 'react'
import styles from './PageLayout.module.css'
import Toast from '../components/Toast';
import { useAppSelector } from '../hooks/reduxhooks';
import { payment } from '../store/slices/paymentSlice';

const PageLayout = ({children}) => {

    const {message,error} = useAppSelector(payment);

  return (
    <div className={styles["container"]}>
      <Head>
        <title>KWABA</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      {message && <Toast message={message} success />}
      {error && <Toast message={error} danger />}
      <div className={styles["header"]}>
        <h1>My Rent</h1>
      </div>
      {children}
    </div>
  );
}

export default PageLayout