import React, { useId, useState } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import numeral from "numeral";
import styles from "../styles/Approval.module.css";
import InputElement from "../components/InputElement";
import SelectInput from "../components/SelectInput";
import Button from "../components/Button";
import PaymentSummary from "../components/PaymentSummary";
import { useAppDispatch, useAppSelector } from "../hooks/reduxhooks";
import {
  changeMonthlyPlan,
  changeRentAmount,
  payment,
} from "../store/slices/paymentSlice";
import Toast from "../components/Toast";
import { submitDetails } from "../store/actionCreators/saveDetails";

const Approval = () => {

  const router = useRouter();
  const dispatch = useAppDispatch();
  const {
    message,
    error,
    loading,
    rentAmount,
    monthlyPlan,
    monthlyPayment,
    monthlyEarning,
    accomodationStatus,
  } = useAppSelector(payment);

  const onChangeInput = (e, name) => {
    dispatch(changeRentAmount({ rentAmount: e.target.value }));
  };

  const updateMonthly = (plan) => {
    dispatch(changeMonthlyPlan({ monthlyPlan: plan }));
  };

  const submitForm = () => {
    dispatch(
      submitDetails(
        {
          rentAmount,
          monthlyPlan,
          monthlyPayment,
          monthlyEarning,
          accomodationStatus,
        },
        () => {
          setTimeout(() => {
            router.push("/");
          }, 3000);
        }
      )
    );
  };

  return (
    <div className={styles["container"]}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {message && <Toast message={message} success />}
      {error && <Toast message={error} danger />}

      <div className={styles["header"]}>
        <h1>My Rent</h1>
      </div>
      <div className={styles["form"]}>
        <div className={styles["form__header"]}>
          <h3>Payment Breakdown</h3>
        </div>
        <div className={styles["form__body"]}>
          <InputElement
            onChange={onChangeInput}
            caption="Rent request amount?"
            name="rent"
            customStyle
            value={`₦${numeral(rentAmount).format("0,0")}`}
          />
          <SelectInput
            plan={monthlyPlan}
            onChange={updateMonthly}
            caption="Monthly payment plan"
          />
          <PaymentSummary
            rent={numeral(rentAmount).format("0,0")}
            payable={numeral(monthlyPayment).format("0,0.00")}
            plan={monthlyPlan}
          />
          <Button
            onclick={submitForm}
            variant="purple"
            text={loading ? "loading..." : "accept"}
          />
        </div>
      </div>
    </div>
  );
};

export default Approval;
